os:
- linux
- osx
language: c
sudo: required
install: bash travis-setup.sh
services:
- docker
before_script:
- export PATH=/anaconda/bin:$PATH
script:
- bash travis-run.sh
- bash travis-post-build.sh
env:
  global:
    secure: s5k02lR16xZOjhPBzz7RR+JLMmE97rYVennYsz2EJolf8dW60n7dqSyk+bxyo0CArjQmrySBDfeA5izzUBDaIn9dL7TadUfeqvff7YQR+AhMI9QE1bKDEzg/1uHwrZzs6626CIAleoy2ujXSIKNewMXWF1bGHnonnsampO1avHdOtsTmHNQhmWMcwHuEEBeVvpec1T+HMbjn+fVhQFI9I/xd2+EUnsSxG1l6giz8PjUkamc5sxfnWN2nAVkm0IBjQw3TmWbFFeIav4LYirIOxtdMRAWvIuPe+JAMu4isNnulAy1xYJg/zY2kTcaSNq+2hYPSSuJcC//NXSSuYvF+BujNdYDmp5MU6n8hnmG39oeEY+iUoREshqZL+p0dtO4WbJg+L98p4Z2iQP8l8m3bAHID+hMPrZ11dpZjfVbbMLQBgmHEdyxjrMUf6G5gFHkAIaUwLD+SRzpCICvxUsS8qnJU/d/SC+vPoaPx0VX64pOEHeJgSA8OSaAG3fYAFg56UUVOxWRCwj27P/RSj5MuEH4ZRkVz5SfkZapU0CmzRhrRJ7fHSVqPSGlnjR049RlrS/wCQwZJqB7vA5wm/vTHF4Kndsmv5d8TF3dxkgDCy3KYLXAOz2E58iq96/C99NfMemzFY0gQpqWOwaUdt3EnbJbI51juoD076vj+klTjsKs=
